import React from "react";

import Navbar from "./navbar/Navbar";
import SloganContainer from "./slogan-container/SloganContainer";
import TryFreeProducts from "./try-free-products/TryFreeProducts";
import Features from "./feature-container/Features";
import Footer from "./footer/Footer";
import feature1 from "./assets/feature01.svg";
import feature2 from "./assets/feature02.svg";
import feature3 from "./assets/feature03.svg";
import india from "./assets/india.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <header className="App-Header">
        <Navbar />
      </header>
      <SloganContainer />
      <div className="App-Features">
        <Features
          title={"Search"}
          subtitle={
            "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen."
          }
          image={feature3}
        />
        <Features
          title={"Select"}
          subtitle={
            "Choose from thousands of options generated by the slogan maker that fit your needs."
          }
          image={feature1}
        />
        <Features
          title={"Stand out"}
          subtitle={"Congrats on your new slogan. It's time to win the world!"}
          image={feature2}
        />
      </div>
      <TryFreeProducts />
      <footer className="App-Footer">
        <Footer />
        <hr className="Footer-Divider" />
        <div className="App-Footer-Trademark">
          <span>Dukaan 2020, All rights reserved.</span>
          <div className="Made-In-India">
            <span>Made in</span>
            <img src={india} alt="india-logo" className="India-logo" />
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;
